create table if not exists public.rooms (
  id text primary key,
  sort_order integer not null unique,
  name text not null,
  building text not null,
  capacity integer not null check (capacity > 0),
  kind text not null,
  amenities jsonb not null default '[]'::jsonb,
  description text not null,
  image_key text not null,
  active boolean not null default true
);

create table if not exists public.blocked_slots (
  id bigint generated by default as identity primary key,
  room_id text not null references public.rooms(id) on delete cascade,
  booking_date date not null,
  start_hour integer not null check (start_hour >= 8 and start_hour < 20),
  end_hour integer not null check (end_hour > start_hour and end_hour <= 20),
  label text not null default 'Lịch sử dụng của nhà trường',
  unique (room_id, booking_date, start_hour, end_hour)
);

create table if not exists public.bookings (
  id text primary key,
  user_id text not null,
  room_id text not null references public.rooms(id),
  room_name text not null,
  booking_date date not null,
  start_hour integer not null check (start_hour >= 8 and start_hour < 20),
  end_hour integer not null check (end_hour > start_hour and end_hour <= 20),
  status text not null default 'confirmed' check (status in ('confirmed', 'cancelled')),
  created_at timestamptz not null default now(),
  cancelled_at timestamptz
);

create index if not exists bookings_room_time_idx
  on public.bookings (room_id, booking_date, status, start_hour, end_hour);
create index if not exists bookings_user_time_idx
  on public.bookings (user_id, booking_date, status, start_hour, end_hour);
create index if not exists blocked_slots_room_time_idx
  on public.blocked_slots (room_id, booking_date, start_hour, end_hour);

alter table public.rooms enable row level security;
alter table public.blocked_slots enable row level security;
alter table public.bookings enable row level security;
revoke all on public.rooms, public.blocked_slots, public.bookings from anon, authenticated;

insert into public.rooms (id, sort_order, name, building, capacity, kind, amenities, description, image_key)
select
  'room-' || n,
  n,
  case (n - 1) % 3
    when 0 then 'Study A3-' || (101 + ((n - 1) / 3))::integer
    when 1 then 'Lab B1-' || (101 + ((n - 1) / 3))::integer
    else 'Library Zone ' || chr(65 + ((n - 1) / 3)::integer)
  end,
  case (n - 1) % 3 when 0 then 'A3' when 1 then 'B1' else 'Thư viện' end,
  (array[6,12,20,30,40,50])[1 + ((n - 1) % 6)],
  case (n - 1) % 3 when 1 then 'Phòng lab' else 'Phòng học' end,
  case (n - 1) % 3
    when 0 then '["Wi-Fi","Máy chiếu","Bảng trắng"]'::jsonb
    when 1 then '["Wi-Fi","Máy chiếu","Máy tính"]'::jsonb
    else '["Wi-Fi","Bảng trắng"]'::jsonb
  end,
  case (n - 1) % 3
    when 1 then 'Không gian thực hành với máy tính, phù hợp làm bài tập và dự án nhóm.'
    else 'Không gian yên tĩnh, đầy đủ ánh sáng cho những buổi tự học và thảo luận nhóm.'
  end,
  case (n - 1) % 3 when 0 then 'study' when 1 then 'lab' else 'library' end
from generate_series(1, 24) as n
on conflict (id) do update set
  sort_order = excluded.sort_order,
  name = excluded.name,
  building = excluded.building,
  capacity = excluded.capacity,
  kind = excluded.kind,
  amenities = excluded.amenities,
  description = excluded.description,
  image_key = excluded.image_key,
  active = true;

create or replace function public.refresh_blocked_slots(p_today date default current_date)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  delete from public.blocked_slots where booking_date < p_today;
  insert into public.blocked_slots (room_id, booking_date, start_hour, end_hour)
  select
    r.id,
    d::date,
    9 + ((r.sort_order - 1) % 3),
    11 + ((r.sort_order - 1) % 3)
  from public.rooms r
  cross join generate_series(p_today, p_today + 6, interval '1 day') d
  on conflict do nothing;

  insert into public.blocked_slots (room_id, booking_date, start_hour, end_hour)
  select r.id, d::date, 15, 17
  from public.rooms r
  cross join generate_series(p_today, p_today + 6, interval '1 day') d
  where r.sort_order % 2 = 1
  on conflict do nothing;
end;
$$;

create or replace function public.create_booking(
  p_id text,
  p_user_id text,
  p_room_id text,
  p_booking_date date,
  p_start_hour integer,
  p_end_hour integer
)
returns setof public.bookings
language plpgsql
security definer
set search_path = public
as $$
declare
  v_room public.rooms%rowtype;
begin
  perform pg_advisory_xact_lock(hashtext(p_booking_date::text || ':' || p_room_id));
  select * into v_room from public.rooms where id = p_room_id and active = true;
  if not found then raise exception 'ROOM_NOT_FOUND'; end if;

  if exists (
    select 1 from public.blocked_slots
    where room_id = p_room_id and booking_date = p_booking_date
      and start_hour < p_end_hour and p_start_hour < end_hour
  ) or exists (
    select 1 from public.bookings
    where status = 'confirmed' and booking_date = p_booking_date
      and start_hour < p_end_hour and p_start_hour < end_hour
      and (room_id = p_room_id or user_id = p_user_id)
  ) then
    raise exception 'BOOKING_CONFLICT';
  end if;

  return query
  insert into public.bookings (
    id, user_id, room_id, room_name, booking_date, start_hour, end_hour
  ) values (
    p_id, p_user_id, p_room_id, v_room.name, p_booking_date, p_start_hour, p_end_hour
  ) returning *;
end;
$$;

create or replace function public.cancel_booking(p_booking_id text, p_user_id text)
returns setof public.bookings
language plpgsql
security definer
set search_path = public
as $$
begin
  if not exists (select 1 from public.bookings where id = p_booking_id and user_id = p_user_id) then
    raise exception 'BOOKING_NOT_FOUND';
  end if;
  return query
  update public.bookings
  set status = 'cancelled', cancelled_at = coalesce(cancelled_at, now())
  where id = p_booking_id and user_id = p_user_id
  returning *;
end;
$$;

revoke all on function public.refresh_blocked_slots(date) from public, anon, authenticated;
revoke all on function public.create_booking(text,text,text,date,integer,integer) from public, anon, authenticated;
revoke all on function public.cancel_booking(text,text) from public, anon, authenticated;
grant execute on function public.refresh_blocked_slots(date) to service_role;
grant execute on function public.create_booking(text,text,text,date,integer,integer) to service_role;
grant execute on function public.cancel_booking(text,text) to service_role;

select public.refresh_blocked_slots(current_date);
